### ISSUE TITLE
category from site-config is ignored

### ISSUE THREAD

**Issue by Benni-chan** [hpsu/nzbget-chrome#18]
As far as I can see, currently the category defined in site configurations is ignored and only the X-DNZB-Category is used.

would be great, if the category from the site could also be used if transmitted (and no X-DNZB-Category is set inside the nzb file).

Background: I tried to add the correct category to links added from fanzub.com
```
if(trParent) {
		var chb = trParent.querySelector('TD INPUT[type=checkbox]');
		if(chb && chb.value) lid = chb.value;
		
		var cat = trParent.querySelector('TD A IMG');
		if (cat && cat.alt) category = cat.alt;
		
	}
```
the category is added correctly to the nzbget-download-link. but in nzbget, the category is still empty

**Comment by hpsu** [comment]
Apparently I never bothered finishing that part of the code, since all the sites I tested sent the header. Thanks for the heads up.
