### ISSUE TITLE
Status in popup not correct

### ISSUE THREAD

**Issue by Amelandbor** [hpsu/nzbget-chrome#19]
If a download is failed, but has had one successful post-processing it will show as success in the popup.

My idea was to use the Total status of the download (*Status* available since v13), willing to make a pull request for that, but let me know if this method is ok with you.

**Comment by hpsu** [comment]
Thanks. I have recently reorganized that code in order to use the history parsing on completed downloads to find out their status. While I were at it I used the .Status-field when available. I don't want to drop support for older versions. Implementation in 5bc4b04e3c0dff435fcbbb4a77380ef2222d1628
