### ISSUE TITLE
notifications after deleting an nzb

### ISSUE THREAD

**Issue by xelfer** [hpsu/nzbget-chrome#20]
I'm receiving a "download complete!" notification after I delete an nzb in the nzbget interface. 

Expected behaviour would be that these only appear when something completes, not just when I delete something from my queue. 

Thanks!

**Comment by hpsu** [comment]
The old implementation only checked if a download we knew about suddenly disappeared and notified the download was "complete". The new implementation actually searches the history to find the status of the completed download and does not notify on manually deleted downloads.

Btw. You can also delete files directly in the popup from the context menu (little black arrow) if you wish.
