### ISSUE TITLE
Clicking icon to go to NZBGet tries to add :port after subdirectory.

### ISSUE THREAD

**Issue by adamtmitchell** [hpsu/nzbget-chrome#22]
I have setup NZBGet so that it is accessible as my.domain.com/nzbget which works fine with the nzbget-chrome, apart from if i click the icon to access the web interface, where it tries and fails to load my.domain.com/nzbget:80 (or my.domain.com/nzbget: if i leave the port blank).

**Comment by outtahere** [comment]
Same issue here. I have nzbget, sonarr etc. being proxied by nginx webserver as per O.P. where nginx makes the request to port 6789 and proxies back to the client on http://webserver/nzbget
If it's any help the webserver rewrite is:
location ~ ^/nzbget($|./*) {
                rewrite /nzbget/(.*) /$1 break;
                proxy_pass http://127.0.0.1:6789;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}
