### ISSUE TITLE
Request: Disable notifications

### ISSUE THREAD

**Issue by scottrobertson** [hpsu/nzbget-chrome#23]
Hey,

Great extension, really useful. 

One thing that would be really awesome is the ability to disable notifications. The reason for this is that I use Pushbullet, and receive notifications from that.

Thanks
Scott

**Comment by hpsu** [comment]
Hi, glad you like it!

This is already implemented in commit 1fad47399fa9d57c30afb575a94d37129608c93f.

You can use the dev-version from github if you want it right now, otherwise it will be in the next official release.
