### ISSUE TITLE
Issue with dognzb and spacing.

### ISSUE THREAD

**Issue by f3bruary22** [hpsu/nzbget-chrome#24]
When an item in the search results is flagged as a 'failure', then there is no download button. This is fine of course, but it causes an issue in the spacing for the 'valid' items.

screenshot 
![image](https://cloud.githubusercontent.com/assets/9111942/5843178/fc934c00-a1aa-11e4-826f-eb3aba30b967.png)

**Comment by Poeles** [comment]
Came here to also notify you of this issue, hope it can be fixed.

**Comment by hpsu** [comment]
Unfortunately, I do not have access to the site. 

I can clearly see that this has to do with an extra table cell container being inserted on downloadable rows. The implementation could be changed to just add the button as a regular IMG next to the other arrow. This would fix the alignment issue but I have no way of testing it. 

@GrimSerious are you still around? :)

**Comment by GrimSerious** [comment]
I'll have a look.

**Comment by jrave** [comment]
Please have a look at https://github.com/hpsu/nzbget-chrome/pull/25 for a fix.

![dognzb_fix](https://cloud.githubusercontent.com/assets/40087/6171435/6061260a-b2e3-11e4-87b3-943dd96f7561.png)

**Comment by hpsu** [comment]
Should be fixed now thanks to @jrave
