### ISSUE TITLE
Request-Method of XMLHttpRequest in addURL function

### ISSUE THREAD

**Issue by oweitman** [hpsu/nzbget-chrome#26]
file: nzbget.js
function: addUrl
line: xhr.open('POST', url); 

normally you download a file with the GET method in the browser.
is there a special reason why you use the POST-Method?
on some sites the "send to nzbget" fails.

**Comment by hpsu** [comment]
I can't think of a reason, no. Frankly, I'm a bit surprised that it has worked for me without issues.

Thanks for reporting!
