### ISSUE TITLE
Authentication Error

### ISSUE THREAD

**Issue by simonszu** [hpsu/nzbget-chrome#27]
Hi,

i am using nzbget behind a reverse proxy with a self signed certificate. I want to use nzbget-chrome as well, but i get an authentication error when entering the hostname (my.host.tld/nzbget/) with protocol HTTPS on port 443 with the correct credentials. Is there any possibility to debug it, or has nzbget problems with reverse proxys?

**Comment by hpsu** [comment]
hmm... In case of a self signed certificate. If you haven't added it manually to chromes cert list, you have to visit the nzbget web-interface and accept the security warning everytime you start your browser before you can use nzbget-chrome. That's an internal security measure of chrome that I cannot control.

If that's not what you mean and you actually enter the pathname in the hostname-field, try with the latest dev release (download a zip of this repo and install manually in chrome:/extensions). I have recently added support for path names.

**Comment by simonszu** [comment]
It's no problem for me to accept the security warning everytime before i can use nzbget-chrome. Currently i have the same procedure with SABnzbd and the SABconnect++ extension. I only mentioned it, because i thought it could prevent nzbget-chrome to check my login credentials, and spawn the authentication error. 

So i actually enter the full path name into the hostname-field, since that's the URL to access nzbget from the plain browser as well. Thanks for mentioning the dev release, i'll try it.
