### ISSUE TITLE
Limit amount of visible items in the queue

### ISSUE THREAD

**Issue by WoLpH** [hpsu/nzbget-chrome#28]
Right now all of the items are displayed by default, since I currently have about 250 items in my queue that's a bit much. It would be nice to simply limit this to a configurable amount (I personally don't need pagination).

**Comment by hpsu** [comment]
I'm not sure it this is needed. Is this a common occurrence? Does the popup become unresponsive with that amount of downloads? 

The complete list is provided by NZBGet whether we display it or not. So I'm not a fan of just cutting the information without providing a way of seeing it all.  

If we do include this limit there should at least be a "Show more..." link at the bottom to show the whole list.

**Comment by WoLpH** [comment]
It's mainly annoying to have to scroll so much, especially since the previous downloads (to see what's finished already) is all the way at the bottom

It's still quite responsive :)

**Comment by hpsu** [comment]
Closing. Should not be an issue anymore with the tabbed interface.
