### ISSUE TITLE
DOGNzb - download button from dropdown menu disappears.

### ISSUE THREAD

**Issue by ghost** [hpsu/nzbget-chrome#35]
When nzbget-chrome is enabled, the 'download nzb' button under the 'Actions' button on the details page disappears.

**Comment by Xploder** [comment]
Second that. Also the quick DL button disappears when you apply a filter (Top Downloads)

**Comment by f3bruary** [comment]
bump, still present. I have to disable the plugin each time I want to download something off the site.

**Comment by Tyrindor** [comment]
Fix this please!
