### ISSUE TITLE
Dropdown no longer working

### ISSUE THREAD

**Issue by mford1** [hpsu/nzbget-chrome#42]
Not sure when this happened, I think it was working a few weeks ago.  I tried v1.3 and v1.4, connecting to nzbget 15.0, running chrome 45.0.2454.101 m.  

It says it's connected and it shows the number of currently downloading items, but when I click the icon nothing happens.

*edit* completely forgot about windows 10 - I did a clean install of it a few weeks ago and I think this is when it stopped working for me.

**Comment by hpsu** [comment]
I cannot reproduce this with any version. Check if you have enabled other extension that prevent the popup from displaying.
