### ISSUE TITLE
Not connecting

### ISSUE THREAD

**Issue by g0d0rz** [hpsu/nzbget-chrome#46]
Hello,

I cannot seem to connect to Nzbget anymore, correct IP and correct port 6789.

NZBGet 16.4
nzbget-chrome 1.3

Any ideas what the issue could be? Everything worked perfectly before.

Thanks.

**Comment by liq456** [comment]
I have the same issue with nzbget 16.4. please help.

**Comment by hpsu** [comment]
See #45. I will push this fix to the chrome web store when I get a chance, in the meantime you can use the development version as an unpacked extension if you can't wait.

**Comment by g0d0rz** [comment]
Thank you! Latest version (not on web store) works!
