### ISSUE TITLE
Bug on NZB.su Details Page- Adds 2 Download Icons On Tab Switching

### ISSUE THREAD

**Issue by war59312** [hpsu/nzbget-chrome#49]
Hi,

Thanks a lot.. Great extension.

Small bug..

On nzb.su details page. 

Each time you change tabs (details, media info, etc.) and switch back to details tab.

2 download icon gets added to the page.

Should only be a single download icon of course.

Should not be adding another download icon just because I switch tabs on the page.

Thanks,

Will

**Comment by hpsu** [comment]
Duplicate of #39 Already fixed in dev version.

**Comment by war59312** [comment]
Whoops and forgot I already had told you.

Sorry.
