### ISSUE TITLE
[Feature Request?] Port not required in settings

### ISSUE THREAD

**Issue by sethrd** [hpsu/nzbget-chrome#53]
I've been setting up reverse proxies through nginx for all my services lately, but am having issues configuring the options with nzbget to connect to a subdomain without a port. It seems that a port is required to save and test the configuration successfully. I'd prefer to not have to keep the ports open in my router though. Other plugins don't have this requirement.

**Comment by delphiactual** [comment]
port 80 when using reverse proxy

**Comment by sethrd** [comment]
Derped on my end. Didn't even think of using 443 for HTTPS connection.
