### ISSUE TITLE
Add download option to my own Spotweb site

### ISSUE THREAD

**Issue by Panja0** [hpsu/nzbget-chrome#56]
Is there a way to add the download button to my own spotweb installation?

**Comment by hpsu** [comment]
It should work out of the box on a clean installation.
nzbgc tries to find the meta generator tag on the site, like this
```<meta name="generator" content="SpotWeb v0.67.28.31">```

So if you have customized it to remove that it won't detect that site as a spotweb installation.

**Comment by Panja0** [comment]
Ok, I will be installing the site over the weekend and did not know that.
Thanks for the prompt reply. I will have a look once installed!
