### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Panja0** [hpsu/nzbget-chrome#60]
More and more I'm using the (new) NZBindexer "Newzleech".
http://www.newzleech.com/

Can this one be added as well?

**Comment by Panja0** [comment]
Why is it closed?

**Comment by hpsu** [comment]
Because I added it. It's available now if you download the dev version and install manually.
Otherwise it will be in the next release

**Comment by Panja0** [comment]
Sorry, didn't notice that. Thanks for adding it!
