### ISSUE TITLE
Initial page loads without stylesheet

### ISSUE THREAD

**Issue by dgcurtis** [hpsu/nzbget-chrome#64]
It's a minor thing but whenever I click on the icon to open up the nzbget web page, I always have to add a / to the end of the url.  Otherwise it doesn't display properly.

**Comment by dgcurtis** [comment]
So it's not a / that needs appending but for some reason, I always have to reload the page.  The initial page load seems to be omitting the stylesheet.  Once it reload the page, it looks normal

**Comment by hpsu** [comment]
This is a duplicate of #62
