### ISSUE TITLE
.nzb is not being sent to nzbget-chrome

### ISSUE THREAD

**Issue by sharafi1981** [hpsu/nzbget-chrome#71]
Hi,

Lately each time I download .nzb file, Chrome prompts me which application do I want to open it with. In the past, all .nzb file would go to nzbget-chrome and get downloaded automatically. 

I tried to remove the extension and add it again from Chrome store and that did not work. I tried to manually install 1.6 but still having the same issue. I also tried to open the file with Chrome and I get a page with xml code. I even downloaded Chrome Beta but still behaving the same. 

Can someone help me with this please?

Thanks. 

PS If I go to "Downloads" in Chrome and then right click on the .nzb file, I get the option to send it to nzbget-chrome. When I do that, it works OK.

**Comment by hpsu** [comment]
Hi! nzbget-chrome has never hijacked links, other than adding the context menu item you describe.

There is a one click download feature is implemented on some sites as a separate download arrow icon.
